apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: git@github.com:rtnpro/argocd-applicationset-examples.git
      files:
      - path: "**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      source:
        repoURL: git@github.com:rtnpro/argocd-applicationset-examples.git
        targetRevision: HEAD
        path: apps/guestbook
      destination:
        server: '{{cluster.address}}'
        namespace: guestbook
