nginx-ingress:
    controller:
      image:
        repository: rtnpro/nginx-ingress-controller-amd64
        tag: "0.9"
      ingressClass: external-ingress
      publishService:
        enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          memory: 256Mi
      affinity:
        podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: release
                    operator: In
                    values:
                    - external-ingress
                  - key: component
                    operator: In
                    values:
                    - controller
                topologyKey: kubernetes.io/hostname
  
      metrics:
        enabled: true
  
      service:
        type: NodePort